skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator = "3XG3SjJFeobck2JCr3zgt7RiHJ2dGtqSsFqCxN5f4N4F"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
